[package]
name = "orange_rs"
version = "0.1.0"
edition = "2021"
resolver = "2"

[lib]
crate-type = ["cdylib", "rlib"]

[[bin]]
name = "orange_rs"
path = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.27"
winit_input_helper = "0.13.0"
pollster = "0.2.5"
image = "0.24.3"
lazy_static = "1.4.0"
instant = { version = "0.1", features = ["stdweb"] }

env_logger = "0.9"
log = "0.4.17"

ultraviolet = {version = "0.9.0", features = ["bytemuck"]}
bytemuck = "1.12.1"
serde = "1.0.144"


[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
wgpu = {version = "0.13.1", features = ["spirv"]}
egui = "0.19.0"
egui-winit = { version = "0.19.0", features = []}
egui-wgpu = "0.19.0"


[target.'cfg(target_arch = "wasm32")'.dependencies]
wgpu = { version = "0.13.1", features = ["webgl"]}
console_error_panic_hook = "0.1.6"
console_log = "0.2.0"
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4.30"
web-sys = { version = "0.3", features = [
    "Document",
    "Window",
    "Element",
]}
