[workspace]
members = ["app", "web", "download_assets"]

[package]
name = "orange_rs"
version = "0.1.0"
authors = ["jaquobia"]
edition = "2021"
resolver = "2"

[lib]
path = "src/lib.rs"

[dependencies]
winit = "0.27"
winit_input_helper = "0.13"
wgpu = "0.14.2"
pollster = "0.2"
image = "0.24"
lazy_static = "1.4"
instant = { version = "0.1", features = ["stdweb"] }
# instant = "0.1"

env_logger = "0.10.0"
log = "0.4"

ultraviolet = {version = "0.9.0", features = ["bytemuck", "int"]}
bytemuck = { version = "1.12", features = ["derive"] }
serde = { version = "1.0", features = ["derive"] }
serde_derive = "1.0.151"
serde_json = "1.0"
# surf = "2.3.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
